baseURL = 'https://janderedev.xyz/'
languageCode = 'en-us'
title = 'janderedev.xyz'
enableGitInfo = true
disableKinds = [ "taxonomy", "term", "RSS" ]

[params.plausible]
  domain = "janderedev.xyz"
  script = "https://stats.fatalerrorcoded.eu/js/stats.js"
  api = "https://stats.fatalerrorcoded.eu/api/stats"
